services:
  backend:
    image: vishnukarthik130474/aadhaar-backend:latest
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: aadhaar-backend
    ports:
      - "5000:5000"
    volumes:
      - ./model:/app/model:ro
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        VITE_API_URL: http://localhost:5000
    container_name: aadhaar-frontend
    ports:
      - "5173:80"
    depends_on:
      - backend
    restart: unless-stopped
